# Generated by Django 6.0.6 on 2026-06-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('excerpt', models.TextField()),
                ('category', models.CharField(choices=[('IA', 'Inteligência Artificial'), ('DevOps', 'DevOps'), ('Arquitetura', 'Arquitetura'), ('Conversao', 'Conversão')], max_length=40)),
                ('read_time', models.PositiveSmallIntegerField(help_text='minutos')),
                ('published_at', models.DateField()),
                ('body', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=120)),
                ('tag', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('techs', models.JSONField(default=list)),
                ('result', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Case Studies',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('revenue_range', models.CharField(blank=True, max_length=80)),
                ('service', models.CharField(blank=True, max_length=80)),
                ('tools', models.CharField(blank=True, max_length=200)),
                ('challenge', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=120)),
                ('business_type', models.CharField(max_length=120)),
                ('revenue', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=120)),
                ('icon_name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('tech_stack', models.JSONField(default=list)),
                ('roi_label', models.CharField(max_length=120)),
                ('roi_value', models.CharField(max_length=120)),
                ('roi_metric_1_label', models.CharField(blank=True, max_length=120)),
                ('roi_metric_1_value', models.CharField(blank=True, max_length=120)),
                ('roi_metric_2_label', models.CharField(blank=True, max_length=120)),
                ('roi_metric_2_value', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
