# Generated by Django 6.0.6 on 2026-06-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='logo',
            field=models.CharField(blank=True, help_text='Caminho relativo em static/, ex: media/cases-logo/cases-logo-tenisbrasil.svg', max_length=200),
        ),
    ]
