# Generated by Django 6.0.6 on 2026-06-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_casestudy_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='card_bg',
            field=models.CharField(blank=True, help_text='CSS de background do card, ex: linear-gradient(135deg, #2a4a7f 0%, #1e3560 100%)', max_length=200),
        ),
    ]
