# Generated by Django 6.0.6 on 2026-06-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_casestudy_card_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='context',
            field=models.TextField(blank=True, verbose_name='Contexto Geral'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='diagram_svg',
            field=models.TextField(blank=True, help_text='Conteúdo interno do <svg viewBox="0 0 300 200"> (apenas os elementos, sem a tag svg)', verbose_name='Diagrama SVG'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='metrics',
            field=models.JSONField(default=list, help_text='Lista de {label, value}, ex: [{"label": "Disponibilidade", "value": "99.99%"}]'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='problem',
            field=models.TextField(blank=True, verbose_name='Problema & Desafio'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='solution',
            field=models.TextField(blank=True, verbose_name='Solução Técnica'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
