# Generated by Django 6.0.6 on 2026-06-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_casestudy_context_casestudy_diagram_svg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL do Projeto'),
        ),
    ]
