# Generated by Django 6.0.6 on 2026-06-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_casestudy_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
    ]
