# Generated by Django 6.0.6 on 2026-06-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactsubmission_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='website',
            field=models.URLField(blank=True, verbose_name='Site da empresa'),
        ),
    ]
